nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= v1.26.0-0 < v1.31.0-0"
    catalog.cattle.io/rancher-version: ">= v2.9.2"
    catalog.cattle.io/ui-extensions-version: ">= 2.0.0"
